name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          export CLOUD_SDK_REPO="cloud-sdk"
          echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin


      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: jiomeet-vidyo

      - name: Configure Docker
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/jiomeet-vidyo/my-repo/flask-app:$GITHUB_SHA .
          docker push asia-south1-docker.pkg.dev/jiomeet-vidyo/my-repo/flask-app:$GITHUB_SHA

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials flask-cluster --zone asia-south1-a --project jiomeet-vidyo
          kubectl set image deployment/flask-app flask-app=asia-south1-docker.pkg.dev/jiomeet-vidyo/my-repo/flask-app:$GITHUB_SHA

